CREATE TRIGGER [LOGGING_TRIGGER]
	ON [dbo].[CONTACT_DATA]
	FOR DELETE, INSERT, UPDATE
	AS
	BEGIN
		SET NOCOUNT ON
		IF EXISTS(SELECT * FROM INSERTED)
		BEGIN
			INSERT 
			INTO [dbo].[LOGS] 
			VALUES (NEXT VALUE FOR LOGS_SEQUENCE, SYSDATETIME(), 'INSERT', 'CONTACT_DATA', 1) 
		END
	END

--CREATE TABLE [dbo].[LOGS]
--(
--	[LOG_ID] INT NOT NULL PRIMARY KEY, 
--    [DATE] DATETIME2 NOT NULL, 
--    [TYPE] VARCHAR(8) NOT NULL, 
--    [TABLE_NAME] VARCHAR(16) NOT NULL, 
--    [ACCOUNT_ID] INT NOT NULL
--)