//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terminal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;Initial Catalog=TerminalMSSQL;User Id=GUEST_DBUSER;Pa" +
            "ssword=eD$nWvgBWeqt|phpa`?xsc6nmsFT7_&#$!~<pyxdhs9LhAlm;Integrated Security=True" +
            "")]
        public string guestConnectionString {
            get {
                return ((string)(this["guestConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;\n            Initial Catalog=TerminalMSSQL;\n         " +
            "   User Id=VALIDATE_CREDENTIALS_LOGIN;\n            Password=validate;\n          " +
            "  Integrated Security=True")]
        public string ValidateCredentials {
            get {
                return ((string)(this["ValidateCredentials"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;\n            Initial Catalog=TerminalMSSQL;\n         " +
            "   User Id=AGENT_LOGIN;\n            Password=agent;\n            Integrated Secur" +
            "ity=True")]
        public string Agent {
            get {
                return ((string)(this["Agent"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;\n            Initial Catalog=TerminalMSSQL;\n         " +
            "   User Id=EMPLOYEE_LOGIN;\n            Password=employee;\n            Integrated" +
            " Security=True")]
        public string Employee {
            get {
                return ((string)(this["Employee"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;\n            Initial Catalog=TerminalMSSQL;\n         " +
            "   User Id=MANAGER_LOGIN;\n            Password=manager;\n            Integrated S" +
            "ecurity=True")]
        public string Manager {
            get {
                return ((string)(this["Manager"]));
            }
        }
    }
}
