CREATE VIEW [dbo].[RESERVATION_VIEW]
	AS SELECT A.[AIRCRAFT_ID], 
	AM.[TYPE] AS 'AIRCRAFT_TYPE', AM.[SIZE] AS 'AIRCRAFT_SIZE' , 
	R.[OBJECT_ID], 
	I.[TYPE] AS 'BUILDING_TYPE', I.[SIZE] AS 'BUILDING_SIZE', 
	R.[BEGIN_DATE], R.[END_DATE] 
	FROM [dbo].[AIRCRAFTS] AS A 
	INNER JOIN [dbo].[AIRCRAFT_MODELS] AS AM ON A.AIRCRAFT_MODEL_ID = AM.AIRCRAFT_MODEL_ID
	INNER JOIN [dbo].[RESERVATIONS] AS R ON A.AIRCRAFT_ID = R.AIRCRAFT_ID
	INNER JOIN [dbo].[INFRASTRUCTURE] AS I ON R.[OBJECT_ID] = I.[OBJECT_ID]
