CREATE TABLE [dbo].[ACCOUNTS]
(
	[ACCOUNT_ID] INT NOT NULL PRIMARY KEY DEFAULT NEXT VALUE FOR [ACCOUNTS_SEQUENCE], 
    [LOGIN] VARCHAR(16) NOT NULL UNIQUE, 
    [PASSWORD] VARCHAR(32) NOT NULL, 
    [PERMISSIONS] TINYINT NOT NULL, 
    [STATUS] TINYINT NOT NULL, 
    [AGENT_ID] INT NULL
)
