CREATE TABLE [dbo].[AGENTS]
(
	[AGENT_ID] INT NOT NULL PRIMARY KEY DEFAULT NEXT VALUE FOR [AGENTS_SEQUENCE], 
    [CONTACT_DATA_ID] INT NOT NULL UNIQUE
	CONSTRAINT U_CONTACT_DATA_ID_A UNIQUE([CONTACT_DATA_ID])
)
