CREATE TABLE [dbo].[CONTACT_DATA]
(
	[CONTACT_DATA_ID] INT NOT NULL PRIMARY KEY DEFAULT NEXT VALUE FOR [CONTACT_DATA_SEQUENCE], 
    [NAME] VARCHAR(32) NOT NULL, 
    [ADDRESS1] VARCHAR(60) NOT NULL, 
    [ADDRESS2] VARCHAR(60) NULL, 
    [CITY] VARCHAR(32) NOT NULL, 
    [POSTAL_CODE] VARCHAR(10) NOT NULL, 
    [EMAIL] VARCHAR(60) NOT NULL, 
    [PHONE_NUMBER] VARCHAR(32) NOT NULL
)
