PRINT N'Inserting values into [dbo].[AGENTS]...';
INSERT INTO [TerminalMSSQL].[dbo].[AGENTS]
VALUES 
(NEXT VALUE FOR [AGENTS_SEQUENCE],  2),
(NEXT VALUE FOR [AGENTS_SEQUENCE],  4),
(NEXT VALUE FOR [AGENTS_SEQUENCE],  6),
(NEXT VALUE FOR [AGENTS_SEQUENCE],  8),
(NEXT VALUE FOR [AGENTS_SEQUENCE],  10),
(NEXT VALUE FOR [AGENTS_SEQUENCE],  12)
