PRINT N'Inserting values into [dbo].[AIRCRAFT_MODELS]...';
INSERT INTO [TerminalMSSQL].[dbo].[AIRCRAFT_MODELS]
VALUES 
(NEXT VALUE FOR [AIRCRAFT_MODELS_SEQUENCE],  'PASS', 'WIDE', 'A310','Airbus'),
(NEXT VALUE FOR [AIRCRAFT_MODELS_SEQUENCE],  'PASS', 'WIDE', 'A310','AirbusS'),
(NEXT VALUE FOR [AIRCRAFT_MODELS_SEQUENCE],  'PASS', 'WIDE', 'A330','Airbus'),
(NEXT VALUE FOR [AIRCRAFT_MODELS_SEQUENCE],  'PASS', 'WIDE', 'A380','Airbus'),
(NEXT VALUE FOR [AIRCRAFT_MODELS_SEQUENCE],  'CARGO', 'WIDE', 'A330','Airbus'),
(NEXT VALUE FOR [AIRCRAFT_MODELS_SEQUENCE],  'PASS', 'WIDE', '737','Boeing'),
(NEXT VALUE FOR [AIRCRAFT_MODELS_SEQUENCE],  'PASS', 'WIDE', '747','Boeing'),
(NEXT VALUE FOR [AIRCRAFT_MODELS_SEQUENCE],  'PASS', 'WIDE', '777','Boeing'),
(NEXT VALUE FOR [AIRCRAFT_MODELS_SEQUENCE],  'PASS', 'WIDE', '787','Boeing'),
(NEXT VALUE FOR [AIRCRAFT_MODELS_SEQUENCE],  'CARGO', 'WIDE', '737','Boeing'),
(NEXT VALUE FOR [AIRCRAFT_MODELS_SEQUENCE],  'PASS', 'NARROW', 'Tu-154','Tupolev'),
(NEXT VALUE FOR [AIRCRAFT_MODELS_SEQUENCE],  'PASS', 'NARROW', 'E-170','Embraer'),
(NEXT VALUE FOR [AIRCRAFT_MODELS_SEQUENCE],  'PASS', 'NARROW', 'Tu-144','Tupolev')