PRINT N'Inserting values into [dbo].[CLIENTS]...';
INSERT INTO [TerminalMSSQL].[dbo].[CLIENTS]
VALUES 
(NEXT VALUE FOR [CLIENTS_SEQUENCE],  1),
(NEXT VALUE FOR [CLIENTS_SEQUENCE],  3),
(NEXT VALUE FOR [CLIENTS_SEQUENCE],  5),
(NEXT VALUE FOR [CLIENTS_SEQUENCE],  7),
(NEXT VALUE FOR [CLIENTS_SEQUENCE],  9),
(NEXT VALUE FOR [CLIENTS_SEQUENCE],  11)