PRINT N'Inserting values into [dbo].[RESERVATIONS]...';
--CREATE TABLE [dbo].[RESERVATIONS]
--(
--	[RESERVATIONS_ID] INT NOT NULL PRIMARY KEY, 
--    [AIRCRAFT_ID] VARCHAR(8) NOT NULL, 
--    [OBJECT_ID] INT NOT NULL, 
--    [BEGIN_DATE] DATETIME2 NOT NULL, 
--    [END_DATE] DATETIME2 NOT NULL, 
--    [CYCLE_ID] INT NULL, 
--    [IS_FINALIZED] BIT NOT NULsL
--)
INSERT INTO [TerminalMSSQL].[dbo].[RESERVATIONS]
VALUES 
--(RESERVATIONS_ID,  AIRCRAFT_ID, OBJECT_ID, BEGIN_DATE, END_DATE, CYCLE_ID, IS_FINALIZED),
--YYYY-MM-DDThh:mm:ss
(NEXT VALUE FOR [AIRCRAFT_MODELS_SEQUENCE],  'LOT3256', 13, '2016-11-10T16:45:00', '2016-11-10T18:45:00', NULL, 0)
